services:
  - type: web
    name: telegram-wallet-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install wheel setuptools
      pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "8219716285"
      - key: CURRENCY
        value: "S.P"
